//package com.ated.o2o.entity;
//
//import io.swagger.annotations.ApiModel;
//import lombok.Builder;
//import lombok.Data;
//
//import javax.persistence.Entity;
//import javax.persistence.Table;
//import java.io.Serializable;
//import java.util.Date;
//import java.util.List;
//
///**
// * @author zengwx
// */
//@Data
//@Entity
//@Builder
//@Table(name="DMI_DEVICE_INFO")
//@ApiModel(value = "account", description = "设备收款账号表")
//public class DeviceInfo implements Serializable {
//
//	private static final long serialVersionUID = -2074679278051954796L;
//
//	private List<DeviceAccount> deviceAccounts;
//	private List<GroupPayment> groupPayment;
//
//
//	private Integer fiveFullLoad;
//	private Integer fiveAlarmNum;
//	private Integer oneAlarmNum;
//	private Integer oneFullLoad;
//    private Long deviceId;
//    private Integer maxChnNum;
//	private Integer maxSlotTotalCapacity;
//	private Integer type;
//    private Long groupId;
//    private Long deviceDefId;
//    private Long pointId;
//    private String mac;
//    private String deviceCode;
//    private String deviceType;
//    private String deviceArea;
//    private String isIndoor;
//    private String address;
//    private String pointAddress;
//    private String screenType;
//    private String screenSize;
//    private String screenDire;
//    private String screenRatio;
//    private String playFomat;
//    private String audio;
//    private String netType;
//    private String devcieDefName;
//    private String placeType;
//    private String envPng;
//    private String adminPwd;
//    private String openPwd;
//    private String onlineState;
//    private String userState;
//    private Long createStaff;
//    private String createStaffName;
//    private Date createTime;
//    private Long modifierStaff;
//    private String modifierStaffName;
//    private Date modifierTime;
//    private String admin;
//    private String adminPhone;
//    private String longCor;
//    private String dimCor;
//    private String advAuditType;
//    private String osVer;
//    private String manufator;
//    private String brnd;
//    private String isCool;
//    private String isHeating;
//    private Date operateBgTime;
//    private Date operateEdTime;
//    private Date regisTime;
//    private Date onlineTime;
//    private Date offlineTime;
//    private String replenishmentSatff;
//    private String replenishmentSatffName;
//    private String replenishmentSatffPhone;
//    private String maintenanceSatff;
//    private String maintenanceSatffName;
//    private String maintenanceSatffPhone;
//    private String stockSatff;
//    private String stockSatffName;
//    private String stockSatffPhone;
//    private String deviceName;
//    private String cooperationMode;
//    private String flowCardNumber;
//    private String isTemperature;
//    private String driveBoardType;
//    private String motorType;
//    private String cargoWayType;
//    private String gratingType;
//    private String deviceGrating;
//    private String isCamera;
//    private String moneyInlet;
//    private String defaultCollectionMode;
//    private String banknotesNumberMax;
//    private String gameMode;
//    private String serviceTel;
//    private Long channelNums;
//    private String canalStart;
//    private String isBind;
//    private String video;
//    private String doc;
//    private String pic;
//    private Long lessTimes;
//    private String linkId;
//    private String state;
//    private String compName;
//    private String lineName;
//    private String pointName;
//    private String shortName;
//    private String deviceDefCode;
//    private String appVer;
//    private String  doorState;
//    private Integer paperNum;
//    private String chnCode;
//    private Long price;
//    private String goodsCode;
//    private Long goodsId;
//    private String goodsName;
//    private Integer prodNum;
//    private Integer fullNum;
//    private Date stateTime;
//    private String fullName;
//    private Integer tenCion;
//    private Integer fiveCion;
//    private Integer deposite;
//    private Integer withDraw;
//    private Float denomination;
//    private String cType;
//    private String currency;
//    private String deviceState;
//    private String driveState;
//    private String lightSensor;
//    private String gameState;
//    private String onBuss;
//    private String hardWare;
//    private String paperIssue;
//    private String chamberId;
//    private Float temperate;
//    private Date operTime;
//    private Long totalPrice;
//    private Long numbers;
//    private Float sumMoney;
//    private Integer sumPay;
//	private Float ccbMoney;
//	private Integer ccbPayWay;
//	private Float wxMoney;
//    private Integer wxPayWay;
//    private Float aliMoney;
//    private Integer aliPayWay;
//    private Float moneyMoney;
//    private Integer moneyPayWay;
//    private String payWay;
//    private Integer totalWithDraw;
//    private Integer totalDeposite;
//    private Float totalTrad;
//    private Float blance;
//    private Float reportBlance;
//    private String isEr;
//    private Date updateTime;
//    private Integer lastNum;
//    private Float leftTemperate;
//    private Float rightTemperate;
//    private Long lowSecureNum;
//    private String zoneName;
//    private String columnName;
//    private String updateColumnValue;
//    private String columnValue;
//    private String coinState;
//    private String lastNumStr;
//    private String intervalTime;
//    private Integer unOut;
//    private Double unOutTotalPrice;
//    private String devcieDefCode;
//    private String bgTime;
//    private String edTime;
//    private Date firstSaleTime;
//    private String scene;
//    private Integer daySales;
//    private Long deviceOnlineNumber;
//    private String deviceOfflineNumberTrans;
//    private String deviceOnlineNumberTrans;
//    private String lastNumTrans;
//    private String onlineStateTrans;
//    private Date aone;
//    private Date atwo;
//    private Date athree;
//    private Date afour;
//    private Date afive;
//    private Date asix;
//   	private String exportDateTime;
//   	private Boolean autoSafety;
//	private Long five;
//	private Long ten;
//    private String groupName;
//    private Long totalNumber;
//    private Long lastNumber;
//    private Long safeNumber;
//    private Long needNumber;
//    private String onlineNumber;
//    private String offlineNumber;
//    private String noDealNumber;
//    private String number;
//    private String lastEmpty;
//    private String shortCoin;
//    private String orderState;
//    private String refundState;
//    private Long payId;
//    private Long orderId;
//    private Long chnId;
//    private Integer coupon;
//    private Double couponTotalPrice;
//    private Integer priceNum;
//    private Double priceValue;
//
//
//}
